### PR TITLE
Use Token.new to create tokens, check possible types.

### PR DESCRIPTION
**Pull request by denispeplin**

### CODE REVIEW

**Comment by fabrik42** [comment]
Looks good to me. Maybe using something like `Map.has_key?` instead of a guard clause would create a better error message for the user. What do you think?

**Comment by denispeplin** [comment]
Something like this?

```elixir
  def new([type: type, literal: literal]) do
    if Map.has_key?(@types, type) do
      %__MODULE__{type: type, literal: literal}
    else
      raise "Token with type #{inspect(type)} is not defined"
    end
  end
```

It'll raise:

```elixir
> Token.new(type: :av, literal: 123)
** (RuntimeError) Token with type :av is not defined
    (monkey) lib/monkey/token.ex:54: Monkey.Token.new/1
```

**Comment by denispeplin** [comment]
Actually, I would add `when is_atom(type) and is_binary(literal)` anyway, just to catch most obvious errors compile time.

**Comment by fabrik42** [comment]
> Token.new(type: :av, literal: 123)
** (RuntimeError) Token with type :av is not defined
    (monkey) lib/monkey/token.ex:54: Monkey.Token.new/1

Very nice! I think this is a helpful message. You could add the other two guards too, if you like.

**Comment by denispeplin** [comment]
Done.

**Comment by fabrik42** [comment]
This is great! Thank you very much! :)

**Pull request merged**
